spring:
  sql:
    init:
      mode: never
  profiles:
    active: # ${ACTIVE_PROFILE}
  datasource:
    url: #jdbc:mysql://${DB_URL}/{DBName}}
    username:  #사용자 이름
    password:  #DB 패스워드
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update #운영 환경에서는 사용하지 않기!!!
        default_batch_fetch_size: 500
logging:
  level:
    root: Info
