spring:
  sql:
    init:
      mode: never
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000     # 미사용 커넥션 30초 후 반환
      connection-timeout: 30000 # 커넥션 요청 대기 시간
      leak-detection-threshold: 25000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        use_sql_comments: true
        default_batch_fetch_size: 500
        format_sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false   # osiv 설정
  jwt:
    key: ${JWT_KEY}
  sigs:
    key: ${CONSUMER_KEY}
    secret: ${CONSUMER_SECRET}
  weather:
    key: ${METEOROLOGICAL_ADMIN_KEY}
  kakao:
    admin_key: ${KAKAO_SERVICE_ADMIN_KEY}
  profiles:
    active: default
  servlet:
    multipart:
      enabled: true
      location: /uploadImg
      max-request-size: 30MB
      max-file-size: 10MB
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: true

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterWrite=10s


logging:
  level:
    root: info
#    org.hibernate.SQL: debug
#    org.hibernate.orm.jdbc.bind: trace
#    org.pknu.weather: info

log:
  config:
    path: /customLog
    filename: custom

api:
  weather:
    forecast-url: http://apis.data.go.kr/1360000/VilageFcstInfoService_2.0
    forecast-value: /getVilageFcst
    service-key: ${SHORT_TERM_FORECAST_API_KEY}
    data-type: JSON

management:
  health:
    db:
      enabled: false
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    s3:
      bucket: weather-pknu-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false

server:
  tomcat:
    mbeanregistry:
      enabled: true

apple:
  public-key-url: https://appleid.apple.com
  client-id: ${CLIENT_ID}
  team-id: ${TEAM_ID}
  key:
    id: ${APPLE_KEY_ID}
    content: ${APPLE_KEY}

fcm:
  project-id: ${FCM_ID}
  service-account: ${FCM_CREDENTIAL}

log-option: prod
