spring:
  sql:
    init:
      mode: never
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 500
    hibernate:
      ddl-auto: none
    open-in-view: false   # osiv 설정
  jwt:
    key: ${JWT_KEY}
  sigs:
    key: ${CONSUMER_KEY}
    secret: ${CONSUMER_SECRET}
  weather:
    key: ${METEOROLOGICAL_ADMIN_KEY}
  profiles:
    active: default
  servlet:
    multipart:
      enabled: true
      location: /uploadImg
      max-request-size: 30MB
      max-file-size: 10MB

logging:
  level:
    root: debug
log:
  config:
    path: /customLog
    filename: custom

api:
  weather:
    service-key: ${SHORT_TERM_FORECAST_API_KEY}
    data-type: JSON

management:
  health:
    db:
      enabled: false
  endpoint:
    health:
      show-details: always
cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    s3:
      bucket: weather-pknu-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false
