name: CD - Deploy to EC2

on:
  workflow_run:
    workflows: ["CI - Build and Push Docker Image"]
    types:
      - completed

jobs:
  # 위 과정에서 푸시한 이미지를 ec2에서 풀받아서 실행시키는 과정
  run-docker-image-on-ec2:
    needs: build-docker-image
    runs-on: self-hosted  # 우분투 서버에서 실행하도록 하는 명령어

    steps:
      # 최신 이미지를 풀받습니다
      - name: Docker pull
        run: sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/github-actions-demo

      # 기존의 컨테이너를 중지시킵니다
      - name: Docker stop container
        run: sudo docker stop $(sudo docker ps -q) 2>/dev/null || true

      # 최신 이미지를 컨테이너화하여 실행시킵니다
      - name: Docker run new container
        run: sudo docker run --name neighborhood_weather_community_app --rm -d -p 8080:8080 ${{ secrets.DOCKER_HUB_USERNAME }}/github-actions-demo

      # 미사용 이미지를 정리합니다
      - name: Delete old Docker image
        run: sudo docker system prune -f
