name: Deploy to CLOUDTYPE
on:
#  push:
#    branches:
#      - dev
  pull_request:
    branches:
      - ci/**
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}

      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: weather-dev/web-programing
          stage: main
          yaml: |
            name: weather
            app: java@17
            options:
              ports: "8080"
              healthz: /helath-check
              env: 
                - name: PROFILE_TYPE
                  value: dev
                - name: DB_URL
                  value: ${{ secrets.DB_DEV_URL }}
                - name: DB_USERNAME
                  value: ${{ secrets.DB_USERNAME }}
                - name: DB_PASSWORD
                  value: ${{ secrets.DB_PASSWORD }}
                - name: SHORT_TERM_FORECAST_API_KEY
                  value: ${{ secrets.SHORT_TERM_FORECAST_API_KEY }} 
                - name: JWT_KEY
                  value: ${{ secrets.JWT_KEY }}
                - name: CONSUMER_KEY
                  value: ${{ secrets.CONSUMER_KEY }}
                - name: CONSUMER_SECRET
                  value: ${{ secrets.CONSUMER_SECRET }}
                - name: S3_ACCESS_KEY
                  value: ${{ secrets.S3_ACCESS_KEY }}
                - name: S3_SECRET_KEY
                  value: ${{ secrets.S3_SECRET_KEY }}
                - name: METEOROLOGICAL_ADMIN_KEY
                  value: ${{ secrets.METEOROLOGICAL_ADMIN_KEY }}
                - name: KAKAO_SERVICE_ADMIN_KEY
                  value: ${{ secrets.KAKAO_SERVICE_ADMIN_KEY }}
                - name: CLIENT_ID
                  value: ${{ secrets.CLIENT_ID }}
                - name: TEAM_ID
                  value: ${{ secrets.TEAM_ID }}
                - name: APPLE_KEY_ID
                  value: ${{ secrets.APPLE_KEY_ID }}
                - name: APPLE_KEY
                  value: ${{ secrets.APPLE_KEY }}
              buildenv: []
              start: |
                mkdir -p ./customLog
                chmod 777 ./customLog
                java -jar ./build/libs/weather-0.0.1-SNAPSHOT.jar
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
                branch: dev
                path: /back
