name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - dev
      - feat/**
      - fix/**
      - refactor/**
      - bug/**
      - config/**
    paths:
      - back/**
      - .github/**

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 환경 변수 설정
      - name: Set up environment variables
        run: |
          echo "SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/testdb" >> $GITHUB_ENV
          echo "SPRING_DATASOURCE_USERNAME=root" >> $GITHUB_ENV
          echo "SPRING_DATASOURCE_PASSWORD=root" >> $GITHUB_ENV
          echo "JWT_KEY=${{ secrets.JWT_KEY }}" >> $GITHUB_ENV
          echo "CONSUMER_KEY=${{ secrets.CONSUMER_KEY }}" >> $GITHUB_ENV
          echo "CONSUMER_SECRET=${{ secrets.CONSUMER_SECRET }}" >> $GITHUB_ENV
          echo "SHORT_TERM_FORECAST_API_KEY=${{ secrets.SHORT_TERM_FORECAST_API_KEY }}" >> $GITHUB_ENV

      # Gradle 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x back/gradlew

      # Gradle을 사용하여 테스트 실행
      - name: Run Tests with Gradle
        working-directory: back
        env:
          SPRING_DATASOURCE_URL: ${{ env.SPRING_DATASOURCE_URL }}
          SPRING_DATASOURCE_USERNAME: ${{ env.SPRING_DATASOURCE_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ env.SPRING_DATASOURCE_PASSWORD }}
          JWT_KEY: ${{ env.JWT_KEY }}
          CONSUMER_KEY: ${{ env.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ env.CONSUMER_SECRET }}
          SHORT_TERM_FORECAST_API_KEY: ${{ env.SHORT_TERM_FORECAST_API_KEY }}
        run: ./gradlew test -i

  build-and-push:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ success() }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Gradle 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x back/gradlew

      # Gradle을 사용하여 빌드 실행 (환경 변수 명시적으로 전달)
      - name: Build with Gradle Wrapper
        working-directory: back
        env:
          SPRING_DATASOURCE_URL: ${{ secrets.DB_URL }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.DB_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.DB_PASSWORD }}
          JWT_KEY: ${{ secrets.JWT_KEY }}
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          SHORT_TERM_FORECAST_API_KEY: ${{ secrets.SHORT_TERM_FORECAST_API_KEY }}
        run: ./gradlew build -i

      # Docker 이미지를 빌드
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/github-actions-demo ./back

      # Docker Hub에 로그인
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      # Docker 이미지를 Docker Hub에 푸시
      - name: Docker Hub push
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/github-actions-demo

  deploy:
    runs-on: self-hosted
    needs: build-and-push
    if: ${{ success() }}

    steps:
      # 최신 Docker 이미지를 풀
      - name: Pull the latest Docker image
        run: sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/github-actions-demo

      # 기존의 Docker 컨테이너를 중지
      - name: Stop the existing container (if any)
        run: |
          if [ "$(sudo docker ps -q)" ]; then
            sudo docker stop $(sudo docker ps -q)
          fi

      # 기존의 Docker 컨테이너를 제거
      - name: Remove the existing container (if any)
        run: |
          if [ "$(sudo docker ps -a -q)" ]; then
            sudo docker rm $(sudo docker ps -a -q)
          fi

      # 새로운 Docker 컨테이너를 실행
      - name: Run the new Docker container
        run: sudo docker run --name neighborhood_weather_community_app --rm -d -p 8080:8080 ${{ secrets.DOCKER_HUB_USERNAME }}/github-actions-demo

      # 사용하지 않는 Docker 이미지를 정리
      - name: Clean up unused Docker images
        run: sudo docker system prune -f --volumes
